### ISSUE TITLE
Prioritize search terms in title

### ISSUE THREAD

**Issue by apnadkarni** [dbohdan/tinyfts#1]
When searching for ABC, it would be nice to list the pages that have ABC in the title at the top (before pages containing ABC only in the content)

**Comment by apnadkarni** [comment]
PS This really pertains to the wiki search engine, not tinyfts per se

**Comment by dbohdan** [comment]
I've implemented a new config option, `title-weight`, in e334edbd9ada4581da05cd1e282c83df421e440d.  The results on [tws.dbohdan.com](https://tws.dbohdan.com) should highly prioritize the document title.  What do you think?

**Comment by apnadkarni** [comment]
Nice. Seems to work quite well.

**Comment by dbohdan** [comment]
:+1:
