### ISSUE TITLE
Internal error in search

### ISSUE THREAD

**Issue by ladayaroslav** [dbohdan/tinyfts#2]
Trying searching for "grammar::fa" triggers:

Error
no such column: grammar

**Comment by dbohdan** [comment]
This is not an internal error, but rather how the [FTS5 query syntax](https://www.sqlite.org/fts5.html) works.  To search for "grammar::fa", put it in double quotes ([example](https://tws.dbohdan.com/search?query=%22grammar%3A%3Afa%22)).  I need to document this better.  Later I may introduce a more conventional (Google-like) query syntax.

**Comment by dbohdan** [comment]
I've changed the default search query syntax to be more like Google, Bing, DuckDuckGo, etc. queries.  Try it out.  Your feedback is welcome.
